--CREATE TABLE RELEASE_PARAMETERS 
--(REPORTID varchar(255 CHAR),
--ADDITIONALINFO varchar(255 CHAR), 
--ATTACHMENT varchar(255 CHAR),
--BUSINESSCONTACT varchar(255 CHAR),
--DESCRIPTION varchar(255 CHAR),
--LOB varchar(255 CHAR),
--NAME varchar(255 CHAR),
--PROGRESSBAR varchar(255 CHAR),
--YEAR varchar(255 CHAR)
--TITLE varchar(255 CHAR),
--QUARTER varchar(255 CHAR),
--RELEASES varchar(255 CHAR),
--PRIMARY KEY ("REPORTID")
-- );
-- 
-- 
-- CREATE TABLE "JIRA_HOLDER_TABLE" 
-- ( 
-- "ID" VARCHAR2(255 CHAR),
-- "EFFORT" VARCHAR2(255 CHAR), 
-- "USAGE" VARCHAR2(255 CHAR), 
-- "STORY" VARCHAR2(255 CHAR), 
-- "BUSINESS" VARCHAR2(255 CHAR),
-- PRIMARY KEY ("ID"),
--  KEY `fk_jira` (`REPORTID`),
--  CONSTRAINT `fk_jira` FOREIGN KEY (`REPORTID`) REFERENCES `RELEASE_PARAMETERS` (`REPORTID`)
-- );

insert into RELEASE_PARAMETERS(REPORTID,ADDITIONALINFO,ATTACHMENT,BUSINESSCONTACT,DESCRIPTION,LOB,NAME,PROGRESSBAR,YEAR,TITLE,QUARTER,RELEASES)
values(10001,'InfoField1','AttachmentField1','BusinessContact1','Description1','Cloud','Name1','ProgressBar1','2019','Title1', '08','RD01');

insert into RELEASE_PARAMETERS(REPORTID,ADDITIONALINFO,ATTACHMENT,BUSINESSCONTACT,DESCRIPTION,LOB,NAME,PROGRESSBAR,YEAR,TITLE,QUARTER,RELEASES)
values(10002,'InfoField2','AttachmentField2','BusinessContact2','Description2','On-prim','Name2','ProgressBar2','2017','Title2','07','FD01');

insert into RELEASE_PARAMETERS(REPORTID,ADDITIONALINFO,ATTACHMENT,BUSINESSCONTACT,DESCRIPTION,LOB,NAME,PROGRESSBAR,YEAR,TITLE,QUARTER,RELEASES)
values(10003,'InfoField3','AttachmentField3','BusinessContact3','Description3','Services','Name3','ProgressBar3','2018','Title3','04', 'FD05');

insert into RELEASE_PARAMETERS(REPORTID,ADDITIONALINFO,ATTACHMENT,BUSINESSCONTACT,DESCRIPTION,LOB,NAME,PROGRESSBAR,YEAR,TITLE,QUARTER,RELEASES)
values(10004,'InfoField4','AttachmentField4','BusinessContact4','Description4','Cloud','Name4','ProgressBar4','2020','Title4','07', 'RD10');

insert into RELEASE_PARAMETERS(REPORTID,ADDITIONALINFO,ATTACHMENT,BUSINESSCONTACT,DESCRIPTION,LOB,NAME,PROGRESSBAR,YEAR,TITLE,QUARTER,RELEASES)
values(10005,'InfoField5','AttachmentField5','BusinessContact5','Description5','Services','Name5','ProgressBar5','2019','Title5','02', 'RD01');



insert into JIRA_HOLDER_TABLE(ID,EFFORT,USAGE,STORY,BUSINESS)
values (123,'aa','bb','cc','dd');

insert into JIRA_HOLDER_TABLE(ID,EFFORT,USAGE,STORY,BUSINESS)
values (124,'aa','bb','cc','dd');